### ISSUE TITLE
remove chain without rebuilding whole container

### ISSUE THREAD

**Issue by drandreaskrueger** [javahippie/geth-dev#15]
**Is your feature request related to a problem? Please describe.**
I have changed gasLimit and clique.period (to get to higher TPS), but `docker-compose up` continued the old chain prior to those changes.

**Describe the solution you'd like**
`delete-chain.sh` which (stops nodes; or doesn't even start them yet but) deletes `/root/.ethereum/geth/chaindata` inside all docker containers

**Describe alternatives you've considered**
My brutal workaround now is

    docker rm $(docker ps -a -q); docker rmi $(docker images -q)

but that means to rebuild everything, and that takes time

**Additional context**
I am benchmarking different ethereum based chains, see https://gitlab.com/electronDLT/chainhammer 

your repo looks useful for this, because it is like the quorum [7nodes example](https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes) or the blk.io [crux-quorum-4nodes-docker-compose](https://github.com/blk-io/crux/blob/master/docker/quorum-crux/docker-compose.yaml).

**Comment by javahippie** [comment]
I don't think it would be a docker-y approach to provide a script which cleans the complete chaindata in the images itself. Do you need to clear all chain data often? 
Instead of deleting the containers and images with `docker rm` you could also use `docker-compose down` and `docker-compose up`. As a default `docker-compose down` removes the containers, `docker-compose up` creates them again, but does not need to rebuild as the containers are created again from the exiting images. This takes < 5 seconds on my machine.

**Comment by drandreaskrueger** [comment]
> Do you need to clear all chain data often?

Yes, because I want the different benchmarking runs to be as unbiased as possible. Not sure why but I think I had noticed mild slowdown when doing a 2nd benchmarking on the same chain.

Infos are now here: https://gitlab.com/electronDLT/chainhammer/blob/master/geth.md#docker-stuff
